name: Ben Collins
favicon: null
layout_spectrum: 0.25765
typography_spectrum: 0.6088788793422282
title: 'Triathlete, Speaker and Product Consultant'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e2ded2'
    - '#615c58'
    - '#b90005'
    - '#e84543'
  brandStrength: 0.9559452263638377
  lightness: 0.5
  saturation: 0.7456247918307781
  rhythmicContrast: 0.75
purpose: []
